# Generated by Django 4.2.30 on 2026-07-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weemeet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weelesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WEEMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(help_text='如：四川成都', max_length=30, verbose_name='所在城市')),
                ('address', models.CharField(help_text='活动详细地址', max_length=24, verbose_name='详细地址')),
                ('cost', models.CharField(blank=True, max_length=12, null=True, verbose_name='费用')),
                ('number', models.IntegerField(help_text='人数多少，请只填半角数字', max_length=5, verbose_name='人数规模')),
                ('summary', models.TextField(blank=True, help_text='使用Markdown语法，说明请点击<a href="http://wowubuntu.com/markdown/" target="_blank">这里</a>', null=True, verbose_name='微聚详情')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=models.SET(weemeet.models.get_sentinel_lesson), to='weelesson.weelesson')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
