# Generated by Django 4.2.30 on 2026-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weemeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weemeet',
            name='number',
            field=models.IntegerField(help_text='人数多少，请只填半角数字', verbose_name='人数规模'),
        ),
    ]
