# Generated by Django 4.2.30 on 2026-07-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weelesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(max_length=5, verbose_name='人数规模')),
                ('issue', models.IntegerField(blank=True, help_text='研修期号，如果来研修只做一期，则不必填写', max_length=2, null=True, verbose_name='期号')),
                ('content', models.TextField(blank=True, null=True, verbose_name='研修详情')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('tags', models.CharField(blank=True, max_length=24, null=True, verbose_name='传播标签')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weelesson.weelesson')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
