# Generated by Django 4.2.30 on 2026-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='issue',
            field=models.IntegerField(blank=True, help_text='研修期号，如果来研修只做一期，则不必填写', null=True, verbose_name='期号'),
        ),
        migrations.AlterField(
            model_name='study',
            name='number',
            field=models.IntegerField(verbose_name='人数规模'),
        ),
    ]
