# Generated by Django 4.2.30 on 2026-07-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WEELesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='一个好的名称会是一个良好的开始', max_length=128, verbose_name='微课名称')),
                ('materials', models.TextField(blank=True, help_text='使用Markdown语法，说明请点击<a href="http://wowubuntu.com/markdown/" target="_blank">这里</a>', null=True, verbose_name='学习内容')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='图片尺寸请不要小于300x200px', null=True, upload_to='uploads/weelesson', verbose_name='微课图片')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(blank=True, max_length=140, null=True, verbose_name='微课简介')),
                ('level', models.CharField(blank=True, default=1, max_length=1, null=True, verbose_name='难度等级')),
                ('is_fine', models.BooleanField(blank=True, default=0)),
                ('is_draft', models.BooleanField(blank=True, default=True, verbose_name='存为草稿')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FineLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weelesson.weelesson', unique=True)),
            ],
        ),
    ]
