# Generated by Django 4.2.30 on 2026-07-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weelesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finelesson',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weelesson.weelesson'),
        ),
    ]
