# Generated by Django 4.2.30 on 2026-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='电子信箱')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
