# Generated by Django 4.2.30 on 2026-07-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, help_text='你的常用网络ID等', max_length=64, null=True, unique=True, verbose_name='昵称')),
                ('localtion', models.CharField(blank=True, max_length=24, verbose_name='来自')),
                ('site', models.CharField(blank=True, max_length=120, verbose_name='个人网址')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/mugshots', verbose_name='头像')),
                ('about_me', models.CharField(blank=True, help_text='请不要超过120字', max_length=120, verbose_name='关于我')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmation_key', models.CharField(blank=True, max_length=40, verbose_name='unconfirmed email verification key')),
                ('email_confirmation_key_created', models.DateTimeField(blank=True, null=True, verbose_name='creation date of email confirmation key')),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
